services:
  jus-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "JUSDBUSER"
      POSTGRES_PASSWORD: "JUSDBPASSWORD"
    ports:
      - "5431:5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data


networks:
  default:
    name: jus-network
