services:
  jus-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "JUSDBUSER"
      POSTGRES_PASSWORD: "JUSDBPASSWORD"
    ports:
      - "3332:5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data

  jus-app:
    image: jus
    restart: always
    ports:
      - "3331:8000"
    depends_on:
      - jus-db

networks:
  default:
    name: jus-network
